// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRrXPTh1xTSAYaSYDf58K9ohhNpWp2kV8',
    appId: '1:722129889560:web:7df94bc4cf602a818cd66d',
    messagingSenderId: '722129889560',
    projectId: 'agree-project-92c04',
    authDomain: 'agree-project-92c04.firebaseapp.com',
    storageBucket: 'agree-project-92c04.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6x8qxKOs5rePB6L9uxqttH3Z6GjjtQ-0',
    appId: '1:722129889560:android:2d6c09ea0c7ffa518cd66d',
    messagingSenderId: '722129889560',
    projectId: 'agree-project-92c04',
    storageBucket: 'agree-project-92c04.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMG1PnGEpQ0GBbZXkHD7G8tz9yVZldplU',
    appId: '1:722129889560:ios:1451b628f5863abc8cd66d',
    messagingSenderId: '722129889560',
    projectId: 'agree-project-92c04',
    storageBucket: 'agree-project-92c04.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMG1PnGEpQ0GBbZXkHD7G8tz9yVZldplU',
    appId: '1:722129889560:ios:14bb4137a8c9a2568cd66d',
    messagingSenderId: '722129889560',
    projectId: 'agree-project-92c04',
    storageBucket: 'agree-project-92c04.appspot.com',
    iosBundleId: 'com.example.app.RunnerTests',
  );
}
